# Generated by Django 6.0 on 2025-12-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_usersdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdetails',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
